language: objective-c
osx_image: xcode12.2

env:
  global:
    - NODE_VERSION=stable

before_install:
  - brew tap wix/brew
  - brew install applesimutils
  #install node version manager
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
  #install node
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - nvm alias default $NODE_VERSION

  - brew install yarn
  - yarn global add react-native-cli
  - yarn global add detox-cli

install:
  - yarn install
  #compilation
  - yarn tsc
  # build app
  - make clean
  - travis_wait 20 make build

script:
  - detox clean-framework-cache && detox build-framework-cache
  #run e2e tests
  - yarn test
  